# Generated by Django 3.0.5 on 2020-04-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(blank=True, max_length=500)),
                ('h2', models.CharField(blank=True, max_length=500)),
                ('p', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='OptInPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(blank=True, max_length=500)),
                ('h2', models.CharField(blank=True, max_length=500)),
                ('p', models.CharField(blank=True, max_length=2000)),
                ('btn', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landingpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funnels.LandingPage')),
                ('optinpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funnels.OptInPage')),
            ],
        ),
    ]
