# Generated by Django 3.0.5 on 2020-05-03 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import funnels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgcolor', models.CharField(default='#ffffff', max_length=7)),
                ('cardbgcolor', models.CharField(default='#ffffff', max_length=7)),
                ('cardwidth', models.IntegerField(default=80)),
            ],
        ),
        migrations.CreateModel(
            name='OptInPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(blank=True, max_length=500, null=True)),
                ('h2', models.CharField(blank=True, max_length=500, null=True)),
                ('p', models.CharField(blank=True, max_length=2000, null=True)),
                ('btn', models.CharField(blank=True, max_length=100, null=True)),
                ('settings', models.OneToOneField(default=funnels.models.default_pagesettings, on_delete=django.db.models.deletion.CASCADE, to='funnels.PageSettings')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(blank=True, max_length=500, null=True)),
                ('h2', models.CharField(blank=True, max_length=500, null=True)),
                ('p', models.CharField(blank=True, max_length=2000, null=True)),
                ('settings', models.OneToOneField(default=funnels.models.default_pagesettings, on_delete=django.db.models.deletion.CASCADE, to='funnels.PageSettings')),
            ],
        ),
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landingpage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='funnels.LandingPage')),
                ('optinpage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='funnels.OptInPage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'owner')},
            },
        ),
    ]
