# Generated by Django 3.0.5 on 2020-04-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnel',
            name='landingpage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funnels.LandingPage'),
        ),
        migrations.AlterField(
            model_name='funnel',
            name='optinpage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funnels.OptInPage'),
        ),
    ]
