# Generated by Django 3.0.5 on 2020-04-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0002_auto_20200415_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='h2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='p',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='optinpage',
            name='btn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='optinpage',
            name='h2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='optinpage',
            name='p',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
