# Generated by Django 3.0.5 on 2020-04-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0004_auto_20200415_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optinpage',
            name='funnel',
        ),
        migrations.AddField(
            model_name='funnel',
            name='landing_h1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='funnel',
            name='landing_h2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='funnel',
            name='landing_p',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='funnel',
            name='optin_btn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funnel',
            name='optin_h1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='funnel',
            name='optin_h2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='funnel',
            name='optin_p',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='LandingPage',
        ),
        migrations.DeleteModel(
            name='OptInPage',
        ),
    ]
