# Generated by Django 3.0.5 on 2020-04-18 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funnels', '0006_auto_20200418_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funnels', to=settings.AUTH_USER_MODEL),
        ),
    ]
