# Generated by Django 3.0.5 on 2020-04-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0007_funnel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funnel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
