# Generated by Django 3.0.5 on 2020-04-19 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funnels', '0008_auto_20200419_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(blank=True, max_length=500, null=True)),
                ('h2', models.CharField(blank=True, max_length=500, null=True)),
                ('p', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptInPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(blank=True, max_length=500, null=True)),
                ('h2', models.CharField(blank=True, max_length=500, null=True)),
                ('p', models.CharField(blank=True, max_length=2000, null=True)),
                ('btn', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='funnel',
            name='landing_h1',
        ),
        migrations.RemoveField(
            model_name='funnel',
            name='landing_h2',
        ),
        migrations.RemoveField(
            model_name='funnel',
            name='landing_p',
        ),
        migrations.RemoveField(
            model_name='funnel',
            name='optin_btn',
        ),
        migrations.RemoveField(
            model_name='funnel',
            name='optin_h1',
        ),
        migrations.RemoveField(
            model_name='funnel',
            name='optin_h2',
        ),
        migrations.RemoveField(
            model_name='funnel',
            name='optin_p',
        ),
        migrations.AlterField(
            model_name='funnel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='funnel',
            name='landing_page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='funnels.LandingPage'),
        ),
        migrations.AddField(
            model_name='funnel',
            name='optin_page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='funnels.OptInPage'),
        ),
    ]
