# Generated by Django 3.0.5 on 2020-04-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funnels', '0009_auto_20200419_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funnel',
            old_name='landing_page',
            new_name='landingpage',
        ),
        migrations.RenameField(
            model_name='funnel',
            old_name='optin_page',
            new_name='optinpage',
        ),
    ]
