# Generated by Django 3.0.5 on 2020-04-23 17:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funnels', '0010_auto_20200420_1719'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='funnel',
            unique_together={('name', 'owner')},
        ),
    ]
